monitor = , preferred, auto, 1

$mainMod = SUPER
$terminal = kitty
$browser = firefox

bind = $mainMod, Q, exec, $terminal 
bind = $mainMod, W, killactive 
bind = $mainMod, E, exec, $browser
bind = $mainMod, M, exit
