# Nvidia Settings
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct # needed for running vaapi-driver on later drivers

# Monitors
monitor = HDMI-A-2, 3840x2160@60, 0x0, 2.5
monitor = DP-4, 1920x1080@60, -1280x0, 1.5
monitor = , preferred, auto, 1

# Keybinds
$mainMod = SUPER
$terminal = kitty
$browser = firefox

bind = $mainMod, Q, exec, $terminal 
bind = $mainMod, W, killactive 
bind = $mainMod, E, exec, $browser
bind = $mainMod, M, exit
