name: test commands and stuff
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: cd ~
      - run: git init
      - run: git remote add origin https://github.com/bwfiq/dotfiles
      - run: git fetch
      - run: git checkout -f master
      - run: exit
